import React, { useState} from 'react'
import Head from 'next/head'
import Script from 'next/script'
import { PostCard, Categories, PostWidget } from '../components';
import { getPosts } from '../services'

export default function Home({ posts }) {
  const [visiblePosts, setVisiblePosts] = useState(5);
  const increment = 3;
  return (
    <div className='container mx-auto px-4 lg:px-10 my-8'>
      <Head>
        <title>Inspired Corner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="grid grid-cols-1  lg:grid-cols-12 lg:gap-12">
        <div className="lg:col-span-8 col-span-1 text-center">
          {posts.slice(0, visiblePosts).map((post, index) => (
            <PostCard key={index} post={post.node} />
          ))}
          {visiblePosts < posts.length && (
            <button className="bg-white text-black font-bold py-2 px-4 rounded mb-8" onClick={() => setVisiblePosts(visiblePosts + increment)}>Lebih Banyak Postingan...</button>
          )}
        </div>
        <div className="lg:col-span-4 col-span-1">
          <div className="lg:sticky relative ">
            <PostWidget />
            <Categories />
          </div>
        </div>
      </div>
      <Script type='text/javascript' src='//pl18886241.highrevenuegate.com/2f/96/9b/2f969bd64c6138464e9488895853c964.js' />
    </div>
  )
}

//how change Fetch data at runtime
/*
export async function getStaticProps() {
  const posts = (await getPosts()) || [];

  return {
    props: {posts}
  }
}
*/

export async function getServerSideProps() {
  const posts = await getPosts();

  const sortedPosts = posts.sort((a, b) => {
    return new Date(b.node.date) - new Date(a.node.date);
  });

  // Balik urutan postingan untuk mendapatkan postingan terbaru di atas
  const latestPosts = sortedPosts.reverse();


  return {
    props: {
      posts: latestPosts,
    },
  };
}